apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-argocd-app
  labels:
    app: demo-argocd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-argocd-app
  template:
    metadata:
      labels:
        app: demo-argocd-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        command: ["xxxxxx"]
        ports:
        - containerPort: 80
