apiVersion: v1
kind: Service
metadata:
  name: demo-argocd-app
  namespace: demo-argocd-app
spec:
  selector:
    app: demo-argocd-app
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  type: LoadBalancer